// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.Data;

#nullable disable

namespace Store.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250318231630_NewDb")]
    partial class NewDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Store.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Jackets"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "T-shirts"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Sweaters"
                        });
                });

            modelBuilder.Entity("Store.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price2")
                        .HasColumnType("float");

                    b.Property<double>("Price3")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A cozy and comfortable sweatshirt made from soft fleece, perfect for everyday wear or post-workout relaxation",
                            Manufacturer = "Nike",
                            Name = "Club Fleece Sweatshirt",
                            Price = 100.0,
                            Price2 = 85.0,
                            Price3 = 70.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "A lightweight, breathable pullover designed for maximum comfort, keeping you cool and stylish throughout the day.",
                            Manufacturer = "Nike",
                            Name = "Air Pullover",
                            Price = 110.0,
                            Price2 = 100.0,
                            Price3 = 90.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "An essential piece for any active lifestyle, this sportswear is designed for optimal performance and everyday comfort.",
                            Manufacturer = "Nike",
                            Name = "Sportswear Essential",
                            Price = 80.0,
                            Price2 = 75.0,
                            Price3 = 70.0
                        },
                        new
                        {
                            Id = 4,
                            Description = "A sleek and modern design with a bold flame pattern, adding a touch of edge to your casual look.",
                            Manufacturer = "Hugo Boss",
                            Name = "Danda Flame",
                            Price = 70.0,
                            Price2 = 65.0,
                            Price3 = 60.0
                        },
                        new
                        {
                            Id = 5,
                            Description = "A stylish and versatile piece with sharp, clean lines for a sophisticated yet casual appearance.",
                            Manufacturer = "Hugo Boss",
                            Name = "Dikobra",
                            Price = 90.0,
                            Price2 = 85.0,
                            Price3 = 80.0
                        },
                        new
                        {
                            Id = 6,
                            Description = "Timeless and classic, this regular-fit piece offers a comfortable fit for all-day wear.",
                            Manufacturer = "Hugo Boss",
                            Name = "Regular Fit",
                            Price = 100.0,
                            Price2 = 95.0,
                            Price3 = 85.0
                        },
                        new
                        {
                            Id = 7,
                            Description = "Designed for those who prefer a traditional yet tailored look, this piece combines comfort with a perfect fit.",
                            Manufacturer = "Adidas",
                            Name = "Original fit",
                            Price = 150.0,
                            Price2 = 135.0,
                            Price3 = 115.0
                        },
                        new
                        {
                            Id = 8,
                            Description = "Engineered for performance and style, this piece is perfect for runners or anyone who values movement and comfort.",
                            Manufacturer = "Adidas",
                            Name = "Run It",
                            Price = 180.0,
                            Price2 = 160.0,
                            Price3 = 135.0
                        },
                        new
                        {
                            Id = 9,
                            Description = "Classic black and white design with durable construction, ideal for skaters or anyone who appreciates a street-style look.",
                            Manufacturer = "Adidas",
                            Name = "Skate Black & White",
                            Price = 150.0,
                            Price2 = 140.0,
                            Price3 = 130.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
